

// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).


/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated/Ko.Role.g.ts" />
/// <reference path="Generated/Ko.RoleClaim.g.ts" />
/// <reference path="Generated/Ko.RoleClaimList.g.ts" />
/// <reference path="Generated/Ko.RoleList.g.ts" />
/// <reference path="Generated/Ko.User.g.ts" />
/// <reference path="Generated/Ko.UserClaim.g.ts" />
/// <reference path="Generated/Ko.UserClaimList.g.ts" />
/// <reference path="Generated/Ko.UserList.g.ts" />
/// <reference path="Generated/Ko.UsersRoles.g.ts" />
/// <reference path="Generated/Ko.UsersRolesList.g.ts" />
